version: "3.8"
services:
  redis:
    image: redis
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add: [ SYS_NICE ]
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
  ldap:
    image: osixia/openldap:1.2.3
    volumes:
      - ./ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_ORGANISATION=cjavellana
      - LDAP_DOMAIN=cjavellana.me
      - LDAP_ADMIN_PASSWORD=secret
    ports:
      - 10389:389
      - 10636:636
    command: [--copy-service,  --loglevel, debug]
  web:
    build: .
    depends_on: 
      - db
      - ldap
      - redis
    restart: on-failure
    ports:
      - 8080:8080
    command: webserver
  scheduler:
    build: .
    depends_on: 
      - db
      - web
      - redis
    restart: on-failure
    command: scheduler
    volumes:
      - ./dags:/app/airflow/dags
  flower:
    build: .
    restart: on-failure
    ports:
      - 5555:5555
    depends_on:
      - db
      - web
      - scheduler
      - redis
    command: flower
  worker:
    build: .
    restart: always
    depends_on:
      - db
      - web
      - scheduler
      - redis
    command: worker
